# Generated by Django 5.0.2 on 2024-02-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='data',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
